### ISSUE TITLE
Problem with wfnsym_str in ROHF-vLASSCF calculation

### ISSUE THREAD

**Issue by ruthenium96** [MatthewRHermes/mrh#10]
Hello!

Thank you for your developing of vLASSCF! I'm trying to test it on my own system, but the program doesn't work. As I can understand, the problem lies in the field of PySCF symmetry. My system has C1 point group, so I doesn't need it (I actually tried "symmetry = True" and "symmetry = 'C1'" with setting wfnsyms, vLASSCF threw a different error, but still didn't work). Could you please help me to make it work?

Here is my Python code:

```
import numpy as np
from pyscf import gto
from pyscf import lib
from pyscf.tools import molden
from pyscf import scf, mcscf

from scipy import linalg
from mrh.my_pyscf.fci import csf_solver
from mrh.my_pyscf.mcscf.lasscf_testing import LASSCF
from mrh.my_pyscf.mcscf import lassi

lib.num_threads(16)

mn2 = gto.Mole()
mn2.verbose = 4
mn2.spin = 10
mn2.charge = 0
mn2.basis = 'ccpvdz'
mn2.symmetry = False
mn2.max_memory = 30000 #MB

mn2.atom = '''Mn1      -0.220526000     -0.062956000     -0.110240000
C1        0.212976000      0.001320000      3.306452000
O1       -0.206717000      1.483119000      1.467315000
C1       -0.113906000      1.227320000      2.703872000
C1        0.511126000     -1.192226000      2.626899000
O1        0.540777000     -1.388327000      1.376833000
H1        0.239692000     -0.026450000      4.392908000
H1        0.754218000     -2.063340000      3.266427000
H1       -0.309859000      2.067343000      3.399660000
C1       -2.237596000     -2.374986000     -1.633281000
O1       -0.061304000     -1.381319000     -1.832243000
C1       -0.940425000     -2.235515000     -2.151724000
C1       -2.813904000     -1.566720000     -0.638438000
O1       -2.291529000     -0.580737000     -0.040915000
H1       -2.847613000     -3.180027000     -2.034709000
H1       -3.851116000     -1.823280000     -0.349399000
H1       -0.656907000     -2.963894000     -2.937307000
C1        1.466162000      2.214992000     -2.399411000
C1        2.254133000      0.962941000     -2.005558000
N1        1.956815000      0.520699000     -0.628910000
H1        1.902482000      2.599587000     -3.329431000
N1       -0.777811000      1.774426000     -1.392626000
C1       -0.033515000      2.022504000     -2.640745000
H1        1.985678000      0.135087000     -2.670317000
H1        3.328504000      1.165799000     -2.139814000
H1        2.233153000      1.227895000      0.049818000
H1        2.478805000     -0.323771000     -0.404242000
H1       -0.692922000      2.558389000     -0.748144000
H1       -1.769839000      1.651446000     -1.582092000
H1       -0.420878000      2.905561000     -3.173561000
H1       -0.188980000      1.153140000     -3.290068000
H1        1.620630000      3.003725000     -1.646618000
Mn2      -0.919977448     -2.660046932      7.575109822
C2       -3.036324857     -1.207541508      5.277906904
O2       -1.736879106     -0.640000328      7.212753963
C2       -2.447711012     -0.336825821      6.209796613
C2       -2.945957096     -2.609950989      5.295769534
O2       -2.333548454     -3.338797118      6.129879097
H2       -3.613718781     -0.757846428      4.474002588
H2       -3.481366384     -3.137978448      4.482471753
H2       -2.634252561      0.742755640      6.042873640
C2        1.591903360     -4.787144062      6.626626507
O2       -0.178170078     -4.594100851      8.236838045
C2        0.740902069     -5.237260085      7.648428972
C2        1.579858114     -3.502710233      6.056344050
O2        0.825701541     -2.529929918      6.351332482
H2        2.321364520     -5.495014616      6.241708481
H2        2.324360361     -3.322697393      5.257290177
H2        0.897960385     -6.283789065      7.977319308
C2       -1.202359927     -2.161555425     11.173169538
C2       -2.080995399     -3.267937878     10.583620759
N2       -2.527806101     -2.960314801      9.210717290
H2       -1.103004641     -2.357560765     12.247849067
N2        0.213687043     -1.505199221      9.221980984
C2        0.210509868     -2.039799557     10.595848755
H2       -1.510898645     -4.201480043     10.530671946
H2       -2.936439990     -3.435300466     11.257158733
H2       -3.111810586     -2.126141731      9.194760474
H2       -3.091363752     -3.722171987      8.839159416
H2       -0.188196229     -0.570091911      9.186976244
H2        1.163512199     -1.434119058      8.864320836
H2        0.815536613     -1.416470010     11.273444181
H2        0.675558620     -3.031767480     10.559616352
H2       -1.719351981     -1.192713335     11.091183997
'''
mn2.build()

mn2_rohf = scf.ROHF(mn2)
mn2_rohf.chkfile = 'mn2_rohf.chk'
mn2_rohf.init_guess = 'chk'
mn2_rohf.kernel()

mn2_salas = LASSCF (mn2_rohf, (5,5), (5,5))
mn2_salas = mn2_salas.state_average (np.ones(2) / 2,
    spins=[[5, 5], [5, -5]],
    smults=[[30, 30], [30, 30]],
    charges=[[0, 0], [0, 0]]])


mo_loc = mn2_salas.localize_init_guess ((list (range (32)), list (range (33, 64))), mn2_rohf.mo_coeff)
mn2_salas.kernel (mo_loc)
```

stderr:
```
Traceback (most recent call last):
  File "mn2_salas.py", line 137, in <module>
    mn2_salas.kernel (mo_loc)
  File "path_to_mrh/mrh/my_pyscf/mcscf/lasci.py", line 1268, in kernel
    kernel(self, mo_coeff, ci0=ci0, verbose=verbose, casdm0_fr=casdm0_fr, conv_tol_grad=conv_tol_grad)
  File "path_to_mrh/mrh/my_pyscf/mcscf/lasci.py", line 801, in kernel
    ci0 = get_init_guess_ci (las, mo_coeff, h2eff_sub)
  File "path_to_mrh/mrh/my_pyscf/mcscf/lasci.py", line 1101, in get_init_guess_ci
    ci0_i.append (solver.get_init_guess (norb, nelec, solver.nroots, hdiag_csf)[0])
  File "path_to_mrh/mrh/my_pyscf/fci/csf.py", line 473, in get_init_guess
    return get_init_guess (norb, nelec, nroots, hdiag_csf, self.transformer)
  File "path_to_mrh/mrh/my_pyscf/fci/csf.py", line 59, in get_init_guess
    assert (ncsf_sym >= nroots), "Can't find {} roots among only {} CSFs of symmetry {}".format (nroots, ncsf_sym, wfnsym_str)
NameError: name 'wfnsym_str' is not defined
```
And Python code, generating mn2_rohf.chk:

```
from pyscf import gto
from pyscf import lib
from pyscf.tools import molden
from pyscf import scf

lib.num_threads(8)

mn2 = gto.Mole()
mn2.verbose = 4
mn2.spin = 10
mn2.charge = 0
mn2.basis = 'ccpvdz'
mn2.max_memory = 15000 #MB

mn2.atom = '''Mn1      -0.220526000     -0.062956000     -0.110240000
C1        0.212976000      0.001320000      3.306452000
O1       -0.206717000      1.483119000      1.467315000
C1       -0.113906000      1.227320000      2.703872000
C1        0.511126000     -1.192226000      2.626899000
O1        0.540777000     -1.388327000      1.376833000
H1        0.239692000     -0.026450000      4.392908000
H1        0.754218000     -2.063340000      3.266427000
H1       -0.309859000      2.067343000      3.399660000
C1       -2.237596000     -2.374986000     -1.633281000
O1       -0.061304000     -1.381319000     -1.832243000
C1       -0.940425000     -2.235515000     -2.151724000
C1       -2.813904000     -1.566720000     -0.638438000
O1       -2.291529000     -0.580737000     -0.040915000
H1       -2.847613000     -3.180027000     -2.034709000
H1       -3.851116000     -1.823280000     -0.349399000
H1       -0.656907000     -2.963894000     -2.937307000
C1        1.466162000      2.214992000     -2.399411000
C1        2.254133000      0.962941000     -2.005558000
N1        1.956815000      0.520699000     -0.628910000
H1        1.902482000      2.599587000     -3.329431000
N1       -0.777811000      1.774426000     -1.392626000
C1       -0.033515000      2.022504000     -2.640745000
H1        1.985678000      0.135087000     -2.670317000
H1        3.328504000      1.165799000     -2.139814000
H1        2.233153000      1.227895000      0.049818000
H1        2.478805000     -0.323771000     -0.404242000
H1       -0.692922000      2.558389000     -0.748144000
H1       -1.769839000      1.651446000     -1.582092000
H1       -0.420878000      2.905561000     -3.173561000
H1       -0.188980000      1.153140000     -3.290068000
H1        1.620630000      3.003725000     -1.646618000
Mn2      -0.919977448     -2.660046932      7.575109822
C2       -3.036324857     -1.207541508      5.277906904
O2       -1.736879106     -0.640000328      7.212753963
C2       -2.447711012     -0.336825821      6.209796613
C2       -2.945957096     -2.609950989      5.295769534
O2       -2.333548454     -3.338797118      6.129879097
H2       -3.613718781     -0.757846428      4.474002588
H2       -3.481366384     -3.137978448      4.482471753
H2       -2.634252561      0.742755640      6.042873640
C2        1.591903360     -4.787144062      6.626626507
O2       -0.178170078     -4.594100851      8.236838045
C2        0.740902069     -5.237260085      7.648428972
C2        1.579858114     -3.502710233      6.056344050
O2        0.825701541     -2.529929918      6.351332482
H2        2.321364520     -5.495014616      6.241708481
H2        2.324360361     -3.322697393      5.257290177
H2        0.897960385     -6.283789065      7.977319308
C2       -1.202359927     -2.161555425     11.173169538
C2       -2.080995399     -3.267937878     10.583620759
N2       -2.527806101     -2.960314801      9.210717290
H2       -1.103004641     -2.357560765     12.247849067
N2        0.213687043     -1.505199221      9.221980984
C2        0.210509868     -2.039799557     10.595848755
H2       -1.510898645     -4.201480043     10.530671946
H2       -2.936439990     -3.435300466     11.257158733
H2       -3.111810586     -2.126141731      9.194760474
H2       -3.091363752     -3.722171987      8.839159416
H2       -0.188196229     -0.570091911      9.186976244
H2        1.163512199     -1.434119058      8.864320836
H2        0.815536613     -1.416470010     11.273444181
H2        0.675558620     -3.031767480     10.559616352
H2       -1.719351981     -1.192713335     11.091183997
'''

mn2.build()


mn2_rohf = scf.ROHF(mn2)
mn2_rohf.chkfile = 'mn2_rohf.chk'
mn2_rohf.init_guess = 'huckel'
mn2_rohf.level_shift = 0.2

mn2_rohf.kernel()
```

I have:
Python 3.7.2
PySCF from 6d7208d66650e0fcdce3a3ebdbe189de73c68fb0 branch
MRH from 26af389b0e0b400b5d9bd575a8dffb119c91d9db branch

I'll be grateful for any advice!

**Comment by MatthewRHermes** [comment]
Hey,

Two things are happening here. 1) There is an error in the exception-handling code on line 59 of csf.py, which I have just hotfixed. Thanks for helping me find it! 2) Based on your active space and spins kwargs, the maximum possible value of "smult" is 6. The "smult" kwarg is asking for 2*s_frag + 1 (it stands for Spin MULTiplicity - 1 for singlet, 2 for doublet, etc.). You seem to have entered 2s_frag*(2s_frag+1) instead. The error line with the bug that you tripped is activated because there can be no CSFs with s=14.5 in an active space with only five orbitals.

Sorry about the lack of docstring on state_average.

**Comment by ruthenium96** [comment]
You are right, I have read SA-vLASSCF example code inattentively and entered wrong value of `smult`. I'm happy that my mistake helped to fix the error. :)

Thank you for the quick reply!
