### ISSUE TITLE
lasscf_rdm's LASSCF: spin_sub doesn't get passed in correctly

### ISSUE THREAD

**Issue by joannaqw** [MatthewRHermes/mrh#126]
**input:**
```
from mrh.my_pyscf.mcscf.lasscf_rdm import LASSCF    
from pyscf import gto, scf, lib, mcscf, tools                                                             
from pyscf.mcscf import avas

mol_name='Cr4.xyz'
small={'Cr': '6-31g'}                                                                                          
mol=gto.M(atom='Cr4.xyz',verbose=4,spin=24,charge=0,basis=small)
mol.build()
mf=scf.ROHF(mol)
mf.init_guess='atom'
mf=mf.density_fit()
mf.kernel()
mf=mf.newton()
mf.kernel()
 
ncas,nelecas,guess_mo_coeff=avas.kernel(mf,['Cr 3d', 'Cr 4s'] ,minao=mol.basis)
mc_test = mcscf.CASCI (mf, ncas, nelecas)
tools.molden.from_mo(mol,'Cr4_avas.molden',guess_mo_coeff) 
final_list = [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24]+mc_test.ncore
las=LASSCF(mf,(6,6,6,6),((6,0),(0,6),(6,0),(0,6)),spin_sub=(7,7,7,7)) # 2S+1
guess_mo_sorted=las.sort_mo(final_list,guess_mo_coeff)
mo_localized=las.localize_init_guess(([0],[1],[2],[3]),guess_mo_sorted) 
las.kernel(mo_localized)
```
**xyz file**
4                                                                                                              
 
Cr 0.915000 0.000000 1.255000
Cr -0.915000 0.000000 1.255000
Cr -0.915000 0.000000 -1.255000
Cr 0.915000 0.000000 -1.2550004

**Error:**
```
Traceback (most recent call last):
  File "/project/lgagliardi/qjwang/SQSD/QASM_LUCJ/Cr4/LASSCF/alpha_beta/input2.py", line 34, in <module>
    las.kernel(mo_localized)
  File "/project/lgagliardi/shared/Apps/mrh/my_pyscf/mcscf/lasscf_rdm.py", line 501, in kernel
    kernel(self, mo_coeff, casdm1frs=casdm1frs, casdm2fr=casdm2fr, 
  File "/project/lgagliardi/shared/Apps/mrh/my_pyscf/mcscf/lasscf_rdm.py", line 171, in kernel
    if casdm1frs is None: casdm1frs, casdm2fr = get_init_guess_rdm (las, mo_coeff, h2eff_sub)
  File "/project/lgagliardi/shared/Apps/mrh/my_pyscf/mcscf/lasscf_rdm.py", line 112, in get_init_guess_rdm
    fakeci = las.get_init_guess_ci (mo_coeff=mo_coeff, h2eff_sub=h2eff_sub)
  File "/project/lgagliardi/shared/Apps/mrh/my_pyscf/mcscf/lasci.py", line 514, in get_init_guess_ci
    ci0g = solver.get_init_guess (norb, nelec, solver.nroots, hdiag_csf)
  File "/project/lgagliardi/shared/Apps/mrh/my_pyscf/mcscf/lasscf_rdm.py", line 379, in get_init_guess
    hdiag = fci.make_hdiag_csf (h1s, h2, norb, nelec)
  File "/project/lgagliardi/shared/Apps/mrh/my_pyscf/fci/csf.py", line 506, in make_hdiag_csf
    self.check_transformer_cache ()
  File "/project/lgagliardi/shared/Apps/mrh/my_pyscf/fci/csf.py", line 575, in check_transformer_cache
    self.transformer = CSFTransformer (self.norb, neleca, nelecb, self.smult)
  File "/project/lgagliardi/shared/Apps/mrh/my_pyscf/fci/csfstring.py", line 38, in __init__
    self._update_spin_cache (norb, neleca, nelecb, smult)
  File "/project/lgagliardi/shared/Apps/mrh/my_pyscf/fci/csfstring.py", line 107, in _update_spin_cache
    self.econf_csf_mask = make_econf_csf_mask (norb, neleca, nelecb, smult)
  File "/project/lgagliardi/shared/Apps/mrh/my_pyscf/fci/csfstring.py", line 751, in make_econf_csf_mask
    min_npair, npair_offset, npair_dconf_size, npair_sconf_size, npair_csf_size = get_csfvec_shape (norb, neleca, nelecb, smult)
  File "/project/lgagliardi/shared/Apps/mrh/my_pyscf/fci/csfstring.py", line 842, in get_csfvec_shape
    raise ImpossibleSpinError ("Impossible quantum numbers: s = {}; ms = {}".format (s, ms),
mrh.my_pyscf.fci.csfstring.ImpossibleSpinError: Impossible quantum numbers: s = -3.0; ms = -3.0  
```

**Comment by MatthewRHermes** [comment]
Wow I didn't realize that if I title a commit as "Fix <issue>" that github would just close it automatically. Anyway I put the fix on Midway already so lmk if it doesn't solve the problem.

**Comment by joannaqw** [comment]
It did resolve the error! Thank you Matt, will close this issue.
