### ISSUE TITLE
Undefined symbol when mrh compiled with MKL

### ISSUE THREAD

**Issue by hebrewsnabla** [MatthewRHermes/mrh#22]
I compiled pyscf and latest mrh with MKL 2019u3 or 2020u4, and got undefined symbol error. With 2020u4, running a MCPDFT example gives
```
Traceback (most recent call last):
  File "/share/home/srwang/mrh/examples/mcpdft/h2co_tpbe66_def2svp_edipole.py", line 4, in <module>
    from mrh.my_pyscf import mcpdft
  File "/share/home/srwang/mrh/my_pyscf/mcpdft/__init__.py", line 3, in <module>
    from mrh.my_pyscf.mcpdft.mcpdft import get_mcpdft_child_class
  File "/share/home/srwang/mrh/my_pyscf/mcpdft/mcpdft.py", line 15, in <module>
    from mrh.my_pyscf.mcpdft import pdft_veff
  File "/share/home/srwang/mrh/my_pyscf/mcpdft/pdft_veff.py", line 32, in <module>
    libpdft = load_library('libpdft')
  File "/share/home/srwang/mrh/lib/helper.py", line 21, in load_library
    return numpy.ctypeslib.load_library(libname, _loaderpath)
  File "/share/home/srwang/anaconda3/lib/python3.9/site-packages/numpy/ctypeslib.py", line 158, in load_library
    return ctypes.cdll[libpath]
  File "/share/home/srwang/anaconda3/lib/python3.9/ctypes/__init__.py", line 457, in __getitem__
    return getattr(self, name)
  File "/share/home/srwang/anaconda3/lib/python3.9/ctypes/__init__.py", line 452, in __getattr__
    dll = self._dlltype(name)
  File "/share/home/srwang/anaconda3/lib/python3.9/ctypes/__init__.py", line 382, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /share/apps/intel2020u4/compilers_and_libraries_2020.4.304/linux/mkl/lib/intel64_lin/libmkl_gf_lp64.so: undefined symbol: mkl_blas_dgemm_free
```
If I ran a simple DFT job with only pyscf, there's no problem.
I'm quite confused because there was no such problem when I use mrh a few months ago.

**Comment by hebrewsnabla** [comment]
This problem can be resolved by `export LD_PRELOAD=$MKLROOT/lib/intel64/libmkl_core.so:$MKLROOT/lib/intel64/libmkl_sequential.so`.

**Comment by hebrewsnabla** [comment]
This should be an issue of MKL. Close now.
