### ISSUE TITLE
Issues with running LASSCF

### ISSUE THREAD

**Issue by valay1** [MatthewRHermes/mrh#24]
I am trying to run a LASSCF calculation on a MIL MOF node and trying to calculate ground state energy. 
My input file looks like 
```
  1 import numpy as np
  2 import sys
  3 from pyscf import gto, scf, lib
  4 from pyscf import gto, scf, tools, mcscf
  5 from mrh.my_pyscf.mcscf.lasscf_o0 import LASSCF
  6 from pyscf.mcscf import avas
  7 from pyscf import mcscf
  8 mol_name='Al_Fe_Fe.xyz' # Al-Fe-Fe MOF node
  9 small={'C': 'sto-3g','H': 'sto-3g','O': 'sto-3g','Al': 'cc-pvdz','Fe': 'cc-pvdz'}
 10 large={'C': 'def2-SVP','H': 'def2-SVP','O': 'def2-SVP','Al': 'def2-TZVP','Fe': 'def2-TZVP'}
 11 mol=gto.M(atom='../xyz_files/'+mol_name,verbose=4,spin=9,charge=0,basis=small) #spin = 2S
 12 mol.build()
 13 mf=scf.RHF(mol)
 14 mf=mf.density_fit()
 15 from pyscf.lib import temporary_env
 16 with temporary_env (mf.mol,charge=11, spin=0):
 17     mf.kernel()  # may not converge, proceed nevertheless
 18 tools.molden.from_mo(mol,'hf_mini.molden',mf.mo_coeff)
 19 ncas,nelecas,guess_mo_coeff=avas.kernel(mf,['Fe 3d', 'Fe 4d'],minao=mol.basis)
 20 #gives 23 orbitals for small basis : 0,1,2 are non identifiable, 3-12 are 3d, 13-22 are 4d
 21
 22 mc_test = mcscf.CASCI (mf, ncas, nelecas)
 23 tools.molden.from_mo(mol,'avas.molden',guess_mo_coeff[:,mc_test.ncore:mc_test.ncore+ncas])
 24 #Selection of orbital from previous molden file
 25 final_list=[3,4,5,6,7,8,9,10,11,12]+mc_test.ncore # just doing 3d for now.
 26
 27
 28 las=LASSCF(mf,(5,5),((5,5),(1,0)),spin_sub=(5,6)) # spin is 2S+1
 29 guess_mo_sorted=las.sort_mo(final_list,guess_mo_coeff)
 30 mo_localized=las.localize_init_guess(([17],[19]),guess_mo_sorted)
 31 tools.molden.from_mo(mol,'localized.molden',mo_localized[:,mc_test.ncore:mc_test.ncore+ncas])
 32 #las.max_cycle_macro=50
 33 las.kernel(mo_localized)
```
and I get localized orbitals that I want (3d orbitals on iron centers). However, the kernel function does not work and it gives me the following error. 
```
  1 Traceback (most recent call last):
  2   File "lasscf.py", line 30, in <module>
  3     las.kernel(mo_localized)
  4   File "/home/valayagarawal/mrh/my_pyscf/mcscf/lasci.py", line 891, in kernel
  5     self.ci, h2eff_sub, veff = _kern(mo_coeff=mo_coeff, ci0=ci0, verbose=verbose, \
  6   File "/home/valayagarawal/mrh/my_pyscf/mcscf/lasci_sync.py", line 46, in kernel
  7     ci0 = las.get_init_guess_ci (mo_coeff, h2eff_sub, ci0)
  8   File "/home/valayagarawal/mrh/my_pyscf/mcscf/lasci.py", line 478, in get_init_guess_ci
  9     ci0[ix][iy] = solver.get_init_guess (norb, nelec, solver.nroots, hdiag_csf)[0]
 10   File "/home/valayagarawal/mrh/my_pyscf/fci/csf.py", line 479, in get_init_guess
 11     return get_init_guess (norb, nelec, nroots, hdiag_csf, self.transformer)
 12   File "/home/valayagarawal/mrh/my_pyscf/fci/csf.py", line 59, in get_init_guess
 13     assert (ncsf_sym >= nroots), "Can't find {} roots among only {} CSFs of symmetry {}".format (nroots, ncsf_sym, transformer.wfnsym)
 14 AssertionError: Can't find 1 roots among only 0 CSFs of symmetry None
```

I am unsure why this issue arises.

**Comment by MatthewRHermes** [comment]
That error reflects the request of an impossible set of fragment quantum numbers: there are no quintet CSFs with 5 spin-up and 5 spin-down electrons occupying 5 orbitals, and neither are there any sextet CSFs with 1 spin-up and 0 spin-down electrons. It looks like you transposed the input in line 28. Did you intend to write
```
las=LASSCF(mf,(5,5),((5,1),(5,0)),spin_sub=(5,6))
```
?

**Comment by MatthewRHermes** [comment]
I'm working on better coverage of this type of error with clearer error messages in the [impossible_state](/MatthewRHermes/mrh/tree/impossible_state) branch
