### ISSUE TITLE
LASSCF Class seems broken?

### ISSUE THREAD

**Issue by valay1** [MatthewRHermes/mrh#42]
For some reason the `dev` branch in mrh seems to have LASSCF no longer working. I get the error: 

``` 
  5 Traceback (most recent call last):
  6   File "lasscf.py", line 31, in <module>
  7     las=asyn.LASSCF(mf,(4,5,5),((5,1),(5,0),(5,0)),spin_sub=(5,6,6),verbose=4) # spin is 2S+1
  8   File "/home/valayagarawal/mrh/my_pyscf/mcscf/lasscf_async/lasscf_async.py", line 195, in LASSCF
  9     las = LASSCFNoSymm (mf, ncas_sub, nelecas_sub, **kwargs)
 10   File "/home/valayagarawal/mrh/my_pyscf/mcscf/lasci.py", line 810, in __init__
 11     self.fciboxes.append (self._init_fcibox (smult, nel))
 12   File "/home/valayagarawal/mrh/my_pyscf/mcscf/lasci.py", line 818, in _init_fcibox
 13     return get_h1e_zipped_fcisolver (state_average_n_mix (self, [s], [1.0]).fcisolver)
 14   File "/home/valayagarawal/mrh/my_pyscf/mcscf/addons.py", line 35, in state_average_n_mix
 15     sacasscf.fcisolver = get_sanmix_fcisolver (sacasscf.fcisolver)
 16   File "/home/valayagarawal/mrh/my_pyscf/mcscf/addons.py", line 29, in get_sanmix_fcisolver
 17     sanmix_fcisolver = FCISolver (fcisolvers, weights)
 18 TypeError: __init__() takes 2 positional arguments but 3 were given'''

This was working before I pulled the recent `dev' branch

**Comment by MatthewRHermes** [comment]
Have you also updated PySCF recently? PySCF PR #1859 changed the init signature of some classes and _mrh_ 2aa5817 updated the calling lines to account for this.

**Comment by MatthewRHermes** [comment]
Is this issue resolved now?
