### ISSUE TITLE
ValueError and AssertionError with lasscf_guess.py

### ISSUE THREAD

**Issue by joannaqw** [MatthewRHermes/mrh#52]
**DPS (12,12): C-S (2,2), phenyl (6,6), remaining phenyl (4,4)**
System:
```
 13 mol =gto.M(
 14     atom =  '''
 15  S      -0.06662766 -0.08713146  0.1097645
 16  C       0.54112773 -1.65192847 -0.47516273
 17  C      -1.73586044  0.03955769 -0.50805172
 18  H       0.59152475  0.70755786 -0.76448841
 19  C       1.22979661 -1.7547482  -1.6988194 
 20  C      -2.07129898 -0.37010337 -1.81123555
 21  C       0.30285315 -2.76246362  0.35671596
 22  C      -2.68008002  0.55845697  0.39686593
 23  C       1.68667889 -3.02213353 -2.09695634
 24  C      -3.40768949 -0.23620635 -2.2164931
 25  C       0.75691635 -4.01971829 -0.07076587
 26  C      -4.01198627  0.68278979 -0.03506059
 27  C       1.44638234 -4.14862761 -1.29038134
 28  C      -4.37233537  0.28853087 -1.33450017
 29  H       1.42210829 -0.87483417 -2.32278092
 30  H      -1.321326   -0.79476159 -2.48592977
 31  H      -0.22133354 -2.65214157  1.31206081
 32  H      -2.3876627   0.86037307  1.40804671
 33  H       2.23228964 -3.12464885 -3.03992472
 34  H      -3.69661122 -0.5456836  -3.22558286
 35  H       0.58137955 -4.89741482  0.55852618
 36  H      -4.76517167  1.08430288  0.64947079
 37  H       1.80577767 -5.13147274 -1.61008793
 38  H      -5.41155313  0.3856663  -1.66333622''',
 39     basis = 'cc-pvdz',
 40     charge = 1,
 41     spin =  0,
 42     verbose = 5)
```
Situation#1: 2AOs for the second phenyl
 ```
44 mf = mol.RHF().run()
 46 ncas,nelecas,guess_mo_coeff=avas.kernel(mf,['1 C 2p','S 3p'],minao=mol.basis)
 48 las_list=np.array([45,51,39,41,48,52,59,65,40,49,53,58])
 50 frag_orbs=[['1 C 2py','0 S 3py'],['1 C 2px','4 C 2px','6 C 2px','8 C 2px','10 C 2px','12 C 2px'],['5 C 2px','7 C 2px']]
 51 las=LASSCF(mf,(2,6,4),(2,6,4),spin_sub=(1,1,1))
 52 guess_mo_sorted=las.sort_mo(las_list,guess_mo_coeff)
 53 mo_localized=las.localize_init_guess(frag_orbs,guess_mo_sorted)
 56 las.kernel(mo_localized)
```

ERROR (both dev and master):
```
  3 Traceback (most recent call last):                                                                                                                                                          
  4   File "input.py", line 53, in <module>
  5     mo_localized=las.localize_init_guess(frag_orbs,guess_mo_sorted)
  6   File "/project/lgagliardi/shared/Apps/mrh/my_pyscf/mcscf/lasscf_guess.py", line 167, in localize_init_guess
  7     return _localize (las, frags_orbs, mo_coeff, spin, lo_coeff, fock, ao_ovlp, freeze_cas_spaces=freeze_cas_spaces)
  8   File "/project/lgagliardi/shared/Apps/mrh/my_pyscf/mcscf/lasscf_guess.py", line 72, in _localize
  9     mo_coeff[:,i:j] = mo_las[:,:nlas]
 10 ValueError: could not broadcast input array from shape (241,2) into shape (241,4)
```

Situation#2: 4 or 6AOs for the second phenyl
```
 44 mf = mol.RHF().run()
 46 ncas,nelecas,guess_mo_coeff=avas.kernel(mf,['1 C 2p','S 3p'],minao=mol.basis)
 48 las_list=np.array([45,51,39,41,48,52,59,65,40,49,53,58])
 49 frag_orbs=[['1 C 2py','0 S 3py'],['1 C 2px','4 C 2px','6 C 2px','8 C 2px','10 C 2px','12 C 2px'],['5 C 2px','7 C 2px','9 C 2px','11 C 2px']] OR
 frag_orbs=[['1 C 2py','0 S 3py'],['1 C 2px','4 C 2px','6 C 2px','8 C 2px','10 C 2px','12 C 2px'],['2 C 2px','5 C 2px','7 C 2px','9 C 2px','11 C 2px', '13 C 2px']] 
 51 las=LASSCF(mf,(2,6,4),(2,6,4),spin_sub=(1,1,1))
 52 guess_mo_sorted=las.sort_mo(las_list,guess_mo_coeff)
 53 mo_localized=las.localize_init_guess(frag_orbs,guess_mo_sorted)
 56 las.kernel(mo_localized)
```
ERROR: 
```
  3 Traceback (most recent call last):                                                                                                                                                          
  4   File "input.py", line 53, in <module>
  5     mo_localized=las.localize_init_guess(frag_orbs,guess_mo_sorted)
  6   File "/project/lgagliardi/shared/Apps/mrh/my_pyscf/mcscf/lasscf_guess.py", line 167, in localize_init_guess
  7     return _localize (las, frags_orbs, mo_coeff, spin, lo_coeff, fock, ao_ovlp, freeze_cas_spaces=freeze_cas_spaces)
  8   File "/project/lgagliardi/shared/Apps/mrh/my_pyscf/mcscf/lasscf_guess.py", line 82, in _localize
  9     assert (null_coeff.shape[-1] + ncas == nmo)
 10 AssertionError
```

**Comment by MatthewRHermes** [comment]
I think these are both caused by a bug in `lasscf_guess.py` in the translation from AO strings into AO numbers, because the first fragment always ends up with 3 AOs in _localize and the second and third get 7 when we ask for 6.

**Comment by joannaqw** [comment]
Thank you so much Matt, I will start using and testing the caret and let you know if there's anything else comes up.

**Comment by MatthewRHermes** [comment]
Oh, situation 1 is just impossible mathematically. You are asking for 4 active orbitals and only providing a basis of 2 AOs, so there is no way that can work. If you pass `freeze_cas_spaces=True` then you are building the fragment orbitals from the MO CAS guess instead, but that's highly dangerous.

**Comment by MatthewRHermes** [comment]
What happens specifically in situation 2 without the carets is that two AOs get assigned to both fragment 2 and fragment 3 due to the RegEx lookup matching '11 C 2py' and '12 C 2py' to '1 C 2py' and '2 C 2py', respectively. This duplication causes the overall basis to develop linear dependencies. I've added a check to make sure that all `frags_orbs` entries are unique (again, if you pass `freeze_cas_spaces=True`, you technically can get away with this, but I don't recommend it).

**Comment by MatthewRHermes** [comment]
Once you are satisfied that `localize_init_guess` is working as desired, please close the issue.

**Comment by joannaqw** [comment]
Got it, thank you so much. All my calculations are running without errors now.
